version: '3'

services:
  shortener:
    image: urls
    ports:
      - "8000:8000"
    volumes:
      - db_data:/db
    environment:
      - ROCKET_ALLOWLIST=sibr.dev
      - ROCKET_DBPATH=/db/sled
      - ROCKET_ADDRESS=0.0.0.0

volumes:
  db_data:
